Importing the Dependencies

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data Collection and Processing

In [2]:
# loading the csv data to a Pandas DataFrame
heart_data = pd.read_csv('heart.csv')

In [3]:
# print first 5 rows of the dataset
heart_data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [4]:
# print last 5 rows of the dataset
heart_data.tail()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0

In [5]:
# number of rows and columns in the dataset
heart_data.shape

(1025, 14)

In [6]:
# getting some info about the data
heart_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       1025 non-null   int64  
 1   sex       1025 non-null   int64  
 2   cp        1025 non-null   int64  
 3   trestbps  1025 non-null   int64  
 4   chol      1025 non-null   int64  
 5   fbs       1025 non-null   int64  
 6   restecg   1025 non-null   int64  
 7   thalach   1025 non-null   int64  
 8   exang     1025 non-null   int64  
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64  
 11  ca        1025 non-null   int64  
 12  thal      1025 non-null   int64  
 13  target    1025 non-null   int64  
dtypes: float64(1), int64(13)
memory usage: 112.2 KB


In [7]:
# checking for missing values
heart_data.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [8]:
# statistical measures about the data
heart_data.describe()

age          sex           cp     trestbps        chol  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.00000   
mean     54.434146     0.695610     0.942439   131.611707   246.00000   
std       9.072290     0.460373     1.029641    17.516718    51.59251   
min      29.000000     0.000000     0.000000    94.000000   126.00000   
25%      48.000000     0.000000     0.000000   120.000000   211.00000   
50%      56.000000     1.000000     1.000000   130.000000   240.00000   
75%      61.000000     1.000000     2.000000   140.000000   275.00000   
max      77.000000     1.000000     3.000000   200.000000   564.00000   

               fbs      restecg      thalach        exang      oldpeak  \
count  1025.000000  1025.000000  1025.000000  1025.000000  1025.000000   
mean      0.149268     0.529756   149.114146     0.336585     1.071512   
std       0.356527     0.527878    23.005724     0.472772     1.175053   
min       0.000000     0.000000    71.000000     0.000000     0.000000   
25%       0.000000     0.000000   132.000000     0.000000     0.000000   
50%       0.000000     1.000000   152.000000     0.000000     0.800000   
75%       0.000000     1.000000   166.000000     1.000000     1.800000   
max       1.000000     2.000000   202.000000     1.000000     6.200000   

             slope           ca         thal       target  
count  1025.000000  1025.000000  1025.000000  1025.000000  
mean      1.385366     0.754146     2.323902     0.513171  
std       0.617755     1.030798     0.620660     0.500070  
min       0.000000     0.000000     0.000000     0.000000  
25%       1.000000     0.000000     2.000000     0.000000  
50%       1.000000     0.000000     2.000000     1.000000  
75%       2.000000     1.000000     3.000000     1.000000  
max       2.000000     4.000000     3.000000     1.000000

In [9]:
# checking the distribution of Target Variable
heart_data['target'].value_counts()

1    526
0    499
Name: target, dtype: int64

1 --> Defective Heart

0 --> Healthy Heart

Splitting the Features and Target

In [10]:
X = heart_data.drop(columns='target', axis=1)
y = heart_data['target']

In [11]:
print(X)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2  

In [12]:
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64


Splitting the Data into Training data & Test Data

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, stratify=y, random_state=42)

In [15]:
print(X.shape, X_train.shape, X_test.shape)

(1025, 13) (820, 13) (205, 13)


In [23]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

# Assuming X_train and y_train are your training data
lr_model = LogisticRegression()

# Cross-validated accuracy scores
cv_scores = cross_val_score(lr_model, X_train, y_train, cv=5)

# Mean accuracy
print("Cross-validated accuracy scores:", cv_scores)
print("Mean accuracy:", cv_scores.mean())

# Training data accuracy
lr_model.fit(X_train, y_train)
training_data_accuracy_lr = lr_model.score(X_train, y_train)
print('Accuracy score of the training data:', training_data_accuracy_lr)

# Test data accuracy
test_data_accuracy_lr = lr_model.score(X_test, y_test)
print('Accuracy score of the test data:', test_data_accuracy_lr)

# Confusion Matrix
y_pred_lr = lr_model.predict(X_test)
conf_matrix_lr = confusion_matrix(y_test, y_pred_lr)
print('Confusion Matrix:\n', conf_matrix_lr)

# Classification Report
class_report_lr = classification_report(y_test, y_pred_lr)
print('Classification Report:\n', class_report_lr)


Cross-validated accuracy scores: [0.83536585 0.8597561  0.82926829 0.84146341 0.8597561 ]
Mean accuracy: 0.8451219512195122
Accuracy score of the training data: 0.8524390243902439
Accuracy score of the test data: 0.8048780487804879
Confusion Matrix:
 [[72 28]
 [12 93]]
Classification Report:
               precision    recall  f1-score   support

           0       0.86      0.72      0.78       100
           1       0.77      0.89      0.82       105

    accuracy                           0.80       205
   macro avg       0.81      0.80      0.80       205
weighted avg       0.81      0.80      0.80       205



c:\Users\Shiva\Downloads\healthy_habits-main (3)\healthy_habits-main\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,
c:\Users\Shiva\Downloads\healthy_habits-main (3)\healthy_habits-main\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for al

In [24]:
from sklearn.tree import DecisionTreeClassifier

dt_model = DecisionTreeClassifier()

cv_scores = cross_val_score(dt_model, X_train, y_train, cv=5)
print("Cross-validated accuracy scores:", cv_scores)
print("Mean accuracy:", cv_scores.mean())

dt_model.fit(X_train, y_train)
training_data_accuracy_dt = dt_model.score(X_train, y_train)
print('Accuracy score of the training data:', training_data_accuracy_dt)

test_data_accuracy_dt = dt_model.score(X_test, y_test)
print('Accuracy score of the test data:', test_data_accuracy_dt)

# Confusion Matrix
y_pred_dt = dt_model.predict(X_test)
conf_matrix_dt = confusion_matrix(y_test, y_pred_dt)
print('Confusion Matrix:\n', conf_matrix_dt)

# Classification Report
class_report_dt = classification_report(y_test, y_pred_dt)
print('Classification Report:\n', class_report_dt)


Cross-validated accuracy scores: [0.95731707 0.9695122  0.98780488 0.9695122  0.99390244]
Mean accuracy: 0.975609756097561
Accuracy score of the training data: 1.0
Accuracy score of the test data: 1.0
Confusion Matrix:
 [[100   0]
 [  0 105]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205



In [25]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

cv_scores = cross_val_score(rf_model, X_train, y_train, cv=5)
print("Cross-validated accuracy scores:", cv_scores)
print("Mean accuracy:", cv_scores.mean())

rf_model.fit(X_train, y_train)
accuracy_rf = rf_model.score(X_test, y_test)
print(f'rf Accuracy: {accuracy_rf}')

# Test data accuracy
test_data_accuracy_rf = rf_model.score(X_test, y_test)
print('Accuracy score of the test data:', test_data_accuracy_rf)

# Confusion Matrix
y_pred_rf = rf_model.predict(X_test)
conf_matrix_rf = confusion_matrix(y_test, y_pred_rf)
print('Confusion Matrix:\n', conf_matrix_rf)

# Classification Report
class_report_rf = classification_report(y_test, y_pred_rf)
print('Classification Report:\n', class_report_rf)

Cross-validated accuracy scores: [0.9695122  0.98780488 0.98780488 0.97560976 0.99390244]
Mean accuracy: 0.9829268292682928
rf Accuracy: 1.0
Accuracy score of the test data: 1.0
Confusion Matrix:
 [[100   0]
 [  0 105]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205



In [26]:
import xgboost as xgb

xgb_model = xgb.XGBClassifier()

cv_scores = cross_val_score(xgb_model, X_train, y_train, cv=5)
print("Cross-validated accuracy scores:", cv_scores)
print("Mean accuracy:", cv_scores.mean())

xgb_model.fit(X_train, y_train)
accuracy_xgb = xgb_model.score(X_test, y_test)
print(f'XGBoost Accuracy: {accuracy_xgb}')

# Test data accuracy
test_data_accuracy_xgb = xgb_model.score(X_test, y_test)
print('Accuracy score of the test data:', test_data_accuracy_xgb)

# Confusion Matrix
y_pred_xgb = xgb_model.predict(X_test)
conf_matrix_xgb = confusion_matrix(y_test, y_pred_xgb)
print('Confusion Matrix:\n', conf_matrix_xgb)

# Classification Report
class_report_xgb = classification_report(y_test, y_pred_xgb)
print('Classification Report:\n', class_report_xgb)

Cross-validated accuracy scores: [0.9695122  0.98780488 0.98780488 0.9695122  0.98170732]
Mean accuracy: 0.9792682926829268
XGBoost Accuracy: 1.0
Accuracy score of the test data: 1.0
Confusion Matrix:
 [[100   0]
 [  0 105]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       100
           1       1.00      1.00      1.00       105

    accuracy                           1.00       205
   macro avg       1.00      1.00      1.00       205
weighted avg       1.00      1.00      1.00       205



In [27]:
from sklearn.svm import SVC

svm_model = SVC()

cv_scores = cross_val_score(svm_model, X_train, y_train, cv=5)
print("Cross-validated accuracy scores:", cv_scores)
print("Mean accuracy:", cv_scores.mean())

svm_model.fit(X_train, y_train)
accuracy_svm = svm_model.score(X_test, y_test)
print(f'SVM Accuracy: {accuracy_svm}')

# Test data accuracy
test_data_accuracy_svm = svm_model.score(X_test, y_test)
print('Accuracy score of the test data:', test_data_accuracy_svm)

# Confusion Matrix
y_pred_svm = svm_model.predict(X_test)
conf_matrix_svm = confusion_matrix(y_test, y_pred_svm)
print('Confusion Matrix:\n', conf_matrix_svm)

# Classification Report
class_report_svm = classification_report(y_test, y_pred_svm)
print('Classification Report:\n', class_report_svm)

Cross-validated accuracy scores: [0.75       0.7195122  0.70731707 0.63414634 0.70121951]
Mean accuracy: 0.7024390243902439
SVM Accuracy: 0.7073170731707317
Accuracy score of the test data: 0.7073170731707317
Confusion Matrix:
 [[63 37]
 [23 82]]
Classification Report:
               precision    recall  f1-score   support

           0       0.73      0.63      0.68       100
           1       0.69      0.78      0.73       105

    accuracy                           0.71       205
   macro avg       0.71      0.71      0.70       205
weighted avg       0.71      0.71      0.71       205



In [28]:
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier()

cv_scores = cross_val_score(knn_model, X_train, y_train, cv=5)
print("Cross-validated accuracy scores:", cv_scores)
print("Mean accuracy:", cv_scores.mean())

knn_model.fit(X_train, y_train)
accuracy_knn = knn_model.score(X_test, y_test)
print(f'KNN Accuracy: {accuracy_knn}')

# Test data accuracy
test_data_accuracy_knn = knn_model.score(X_test, y_test)
print('Accuracy score of the test data:', test_data_accuracy_knn)

# Confusion Matrix
y_pred_knn = knn_model.predict(X_test)
conf_matrix_knn = confusion_matrix(y_test, y_pred_knn)
print('Confusion Matrix:\n', conf_matrix_knn)

# Classification Report
class_report_knn = classification_report(y_test, y_pred_knn)
print('Classification Report:\n', class_report_knn)

Cross-validated accuracy scores: [0.73780488 0.7195122  0.75609756 0.68902439 0.69512195]
Mean accuracy: 0.7195121951219512
KNN Accuracy: 0.7219512195121951
Accuracy score of the test data: 0.7219512195121951
Confusion Matrix:
 [[74 26]
 [31 74]]
Classification Report:
               precision    recall  f1-score   support

           0       0.70      0.74      0.72       100
           1       0.74      0.70      0.72       105

    accuracy                           0.72       205
   macro avg       0.72      0.72      0.72       205
weighted avg       0.72      0.72      0.72       205



Building a Predictive System

In [31]:
input_data = (53,1,0,142,226,0,0,111,1,0,2,0,3)

# change the input data to a numpy array
input_data_as_numpy_array= np.asarray(input_data)

# reshape the numpy array as we are predicting for only on instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = rf_model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]== 0):
  print('The Person does not have a Heart Disease')
else:
  print('The Person has Heart Disease')

[1]
The Person has Heart Disease


c:\Users\Shiva\Downloads\healthy_habits-main (3)\healthy_habits-main\.venv\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [32]:
# Save the Model to a .pkl File
import joblib


joblib.dump(rf_model, 'heart.pkl')

['heart.pkl']